[*] Running ...
[*] Dataset loaded: E:\Projects\CO\reevo-main_1/problems/tsp_gls\dataset/train200_dataset.npy with 10 instances.
E:\Projects\CO\reevo-main_1\problems\tsp_gls\gpt.py:34: RuntimeWarning: invalid value encountered in multiply
[*] Instance 0: 10.68945737442298
[*] Instance 1: 10.85625510286599
[*] Instance 2: 10.907904210354918
[*] Instance 3: 10.512771042346486
[*] Instance 4: 10.61836958287239
[*] Instance 5: 10.401780852216266
[*] Instance 6: 11.245195817053379
[*] Instance 7: 10.922515405894655
[*] Instance 8: 10.732249476234825
[*] Instance 9: 10.473963156862935
[*] Average:
10.736046202112483
