[*] Running ...
[*] Dataset loaded: /home/lars/workspace/COP/reevo_2/problems/mkp_aco/dataset/train100_dataset.npz with 5 instances.
Traceback (most recent call last):
  File "/home/lars/workspace/COP/reevo_2/problems/mkp_aco/eval.py", line 58, in <module>
    obj = solve(prize, weight)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/lars/workspace/COP/reevo_2/problems/mkp_aco/eval.py", line 23, in solve
    heu = heuristics(prize.copy(), weight.copy()) + 1e-9
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lars/workspace/COP/reevo_2/problems/mkp_aco/gpt.py", line 7, in heuristics_v2
    aggregated_performance = np.mean(non_linear_scaled_ratio, axis=1)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lars/anaconda3/envs/reevo/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 3504, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lars/anaconda3/envs/reevo/lib/python3.11/site-packages/numpy/core/_methods.py", line 106, in _mean
    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lars/anaconda3/envs/reevo/lib/python3.11/site-packages/numpy/core/_methods.py", line 77, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
